export interface VeylithEvent{
 id?:string;
 type?:string;
 message?:string;
 text?:string;
 channel?:string;
 createdAt?:string;
 created_at?:string;
 timestamp?:string;
 payload?:Record<string,unknown>;
 [key:string]:unknown;
}
export interface VeylithAgent{
 id?:string;
 name?:string;
 role?:string;
 state?:string;
 status?:string;
 [key:string]:unknown;
}
export interface VeylithTeam{
 id?:string;
 project?:unknown;
 current?:unknown;
 team?:VeylithAgent[];
 members?:VeylithAgent[];
 [key:string]:unknown;
}
export interface VeylithProject{
 id?:string;
 name?:string;
 title?:string;
 status?:string;
 state?:string;
 progress?:number;
 createdAt?:string;
 updatedAt?:string;
 completedAt?:string;
 [key:string]:unknown;
}
export interface DashboardData{
 workers?:unknown[];
 workerSlots?:unknown[];
 projects?:VeylithProject[];
 tasks?:unknown[];
 events?:VeylithEvent[];
 metrics?:Record<string,unknown>;
 developmentSteps?:unknown[];
 autonomousTeams?:VeylithTeam[];
 publications?:unknown[];
 stats?:Record<string,unknown>;
 workerPool?:Record<string,unknown>;
 ai?:Record<string,unknown>;
 github?:Record<string,unknown>;
 sandbox?:Record<string,unknown>;
 security?:Record<string,unknown>;
 jobs?:unknown[];
 queue?:unknown;
 [key:string]:unknown;
}
