import "dotenv/config";
import path from "node:path";
import os from "node:os";
export const VERSION="0.8.0";
export const PORT=Number(process.env.PORT||7410);
export const ROOT=path.resolve(process.env.WORKSPACE_ROOT||"./workspaces");
export const DB_PATH=path.resolve(process.env.DATABASE_PATH||"./data/veylith.db");
export const POLL=Number(process.env.WORKER_POLL_MS||2500);
export const METRIC_INTERVAL=Number(process.env.METRIC_INTERVAL_MS||3000);
export const MAX_REPAIR_ATTEMPTS=6;
export const WORKER_ID=`veylith-${os.hostname().toLowerCase().replace(/[^a-z0-9-]/g,"-")}`;
export const JOB_CONCURRENCY=Math.max(1,Number(process.env.JOB_CONCURRENCY||1));
export const JOB_LEASE_MS=Math.max(30000,Number(process.env.JOB_LEASE_MS||120000));
export const JOB_HEARTBEAT_MS=Math.max(5000,Math.min(Number(process.env.JOB_HEARTBEAT_MS||30000),Math.floor(JOB_LEASE_MS/2)));
export const JOB_RETRY_BASE_MS=Math.max(1000,Number(process.env.JOB_RETRY_BASE_MS||5000));
export const AI_PROVIDER=(process.env.AI_PROVIDER||"ollama-cloud").trim().toLowerCase();
export const AI_KEY=process.env.OPENAI_API_KEY?.trim()||"";
export const OPENAI_MODEL=(process.env.OPENAI_MODEL||"gpt-5.6").trim();
export const AI_MODEL=OPENAI_MODEL;
export const OLLAMA_URL=(process.env.OLLAMA_URL||"http://127.0.0.1:11434").replace(/\/+$/,"");
export const OLLAMA_MODEL=(process.env.OLLAMA_MODEL||"qwen2.5-coder:7b").trim();
export const OLLAMA_API_KEY=process.env.OLLAMA_API_KEY?.trim()||"";
export const OLLAMA_CLOUD_URL=(process.env.OLLAMA_CLOUD_URL||"https://ollama.com").replace(/\/+$/,"");
export const OLLAMA_CLOUD_MODEL=(process.env.OLLAMA_CLOUD_MODEL||"qwen3-coder:480b-cloud").trim();
export const GITHUB_TOKEN=process.env.GITHUB_TOKEN?.trim()||"";
export const GITHUB_OWNER=process.env.GITHUB_OWNER?.trim()||"";
export const GITHUB_VISIBILITY=(process.env.GITHUB_REPO_VISIBILITY==="public"?"public":"private") as "private"|"public";
export const GITHUB_ENABLED=Boolean(GITHUB_TOKEN&&GITHUB_OWNER);
export const now=()=>new Date().toISOString();
export const AI_REQUEST_TIMEOUT_MS=Math.max(30000,Number(process.env.AI_REQUEST_TIMEOUT_MS)||180000);
export const AI_REQUEST_MAX_ATTEMPTS=2;
export const AI_RETRY_BASE_DELAY_MS=2000;
export const AI_HEALTH_TIMEOUT_MS=10000;
export const AI_RECOVERY_INTERVAL_MS=60000;
export const AI_CIRCUIT_FAILURE_THRESHOLD=1;
export const AI_CIRCUIT_BASE_COOLDOWN_MS=120000;
export const AI_CIRCUIT_MAX_COOLDOWN_MS=900000;
export const AI_CIRCUIT_SUCCESS_THRESHOLD=1;

